name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # match your local Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run all tests (including costing_service_test.dart)
      - name: Run unit and widget tests
        run: flutter test --coverage

      # Upload coverage report (optional)
      - name: Upload coverage to GitHub summary
        if: always()
        run: |
          echo "### Test Coverage" >> $GITHUB_STEP_SUMMARY
          grep -A 1 "coverage" coverage/lcov.info || echo "Coverage data generated."