name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter 3.35.1 manually
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.35.1 --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit and widget tests
        run: flutter test --coverage